---
- import_tasks: ../tasks/persistant-data.yml

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "eclipse-mosquitto"
    pull: true
    state: 'started'
    ports:
      - "1883:1883"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/mosquitto"
      - "{{ docker_dir }}/{{ container_name }}/data:/mosquitto/data"
      - "{{ docker_dir }}/{{ container_name }}/log:/mosquitto/log"
    restart_policy: unless-stopped

- name: Create a cron backup job for {{ container_name }}
  ansible.builtin.cron:
    name: "container backup {{ container_name }}"
    minute: "0"
    hour: "3"
    weekday: "6"
    job: "$CONTAINER_BACKUP {{ container_name }} > /var/log/cb_{{ container_name }}_`date +$DATE_FORMAT`.log"
