---
- name: Make sure the Mosquitto container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "eclipse-mosquitto"
    pull: true
    state: 'started'
    ports:
      - "1883:1883"
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/mosquitto"
      - "{{ docker_dir }}/{{ container_name }}/data:/mosquitto/data"
      - "{{ docker_dir }}/{{ container_name }}/log:/mosquitto/log"
    restart_policy: unless-stopped
