---
- import_tasks: ../tasks/persistant-data.yml

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "homeassistant/home-assistant:stable"
    pull: yes
    state: 'started'
    network_mode: host
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 60s
      timeout: 10s
      retries: 15
      start_period: 60s

# backup is handled by influxdb cron job.
