---
- import_tasks: ../tasks/persistant-data.yml

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "nodered/node-red:latest"
    pull: yes
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
    ports:
      - "1880:1880"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
    restart_policy: unless-stopped
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:1880/settings"]
        interval: 60s
        timeout: 10s
        retries: 15
        start_period: 30s

- name: Create a cron backup job for {{ container_name }}
  ansible.builtin.cron:
    name: "container backup {{ container_name }}"
    minute: "15"
    hour: "3"
    weekday: "6"
    job: "$CONTAINER_BACKUP {{ container_name }} > /var/log/cb_{{ container_name }}_`date +$DATE_FORMAT`.log"
