- hosts: hjordis
  become: yes

  roles:
    - role: essential
      tags:
        - essential

    - role: user
      tags:
        - user

    - role: docker
      tags:
        - docker

    - role: containers/mosquitto
      tags:
        - mosquitto
        - containers
      when: enable_mosquitto | default(False)
