- hosts: all
  become: yes

  roles:
    - role: system
      tags:
        - system

- hosts: all, !dun
  become: yes

  roles:
    - role: filesystems
      tags:
        - filesystems

    - role: docker
      tags:
        - docker

# Containers

    - role: containers/mosquitto
      tags: [ containers, mosquitto ]
      when: "'mosquitto' in selected_containers"

    - role: containers/influxdb
      tags: [ containers, influxdb ]
      when: "'influxdb' in selected_containers"

    - role: containers/homeassistant
      tags: [ containers, homeassistant ]
      when: "'homeassistant' in selected_containers"

    - role: containers/nodered
      tags: [ containers, nodered ]
      when: "'nodered' in selected_containers"

    - role: containers/grafana
      tags: [ containers, grafana ]
      when: "'grafana'in selected_containers"

    - role: containers/telegraf
      tags: [ containers, telegraf ]
      when: "'telegraf'in selected_containers"
