- hosts: all
  become: yes

  roles:
    - role: system
      tags:
        - system

    - role: filesystems
      tags:
        - filesystems

    - role: docker
      tags:
        - docker

  tasks:
    - name: Install containers
      include_role:
        name: containers/{{ item }}
        apply:
          tags: containers
      tags: containers
      with_items: "{{ selected_containers }}"
