- hosts: all
  become: yes

  pre_tasks:
    - name: Remove snap functionality
      when: ansible_facts['distribution'] == 'Ubuntu'
      import_tasks: tasks/remove_snaps.yml
      tags: nosnaps

  roles:
    - role: essential
      tags:
        - essential

    - role: user
      tags:
        - user

    - role: filesystems
      tags:
        - filesystems

    - role: docker
      tags:
        - docker

- hosts: hjordis
  become: yes

  roles:
    - role: containers/mosquitto
      tags:
        - mosquitto
        - containers
      when: enable_mosquitto | default(False)

    - role: containers/influxdb
      tags:
        - influxdb
        - containers
      when: enable_influxdb | default(False)
