- hosts: all
  become: yes

  roles:
    - role: system
      tags:
        - system

    - role: filesystems
      tags:
        - filesystems

    - role: docker
      tags:
        - docker

- hosts: hjordis
  become: yes

  roles:
    - role: containers/mosquitto
      tags:
        - mosquitto
        - containers
      when: enable_mosquitto | default(False)

    - role: containers/influxdb
      tags:
        - influxdb
        - containers
      when: enable_influxdb | default(False)
