---
- name: Ubuntu specific tasks
  become: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
  - name: Remove cloud-config to avoid boot delay
    apt:
      name: cloud-config
      state: absent

- name: Generate the locale (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    upgrade: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Replace the hostname entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'

- name: Allow 'sudo' group to have passwordless sudo
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#(.*)PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify:
   - Restart SSH daemon
