---
- import_tasks: ../tasks/persistant-data.yml

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "grafana/grafana-oss"
    pull: yes
    state: 'started'
    user: "{{ guid }}"
    groups: "{{ guid }}"
    env:
      "TZ": "{{ timezone }}"
    ports:
      - "3000:3000"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/var/lib/grafana"
    restart_policy: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30

- name: Create a cron backup job for {{ container_name }}
  ansible.builtin.cron:
    name: "container backup {{ container_name }}"
    minute: "15"
    hour: "3"
    weekday: "6"
    job: "$CONTAINER_BACKUP {{ container_name }} > /var/log/cb_{{ container_name }}_`date +$DATE_FORMAT`.log"
