---
- name: Create a login user
  user:
    name: "{{ username  }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - "{{ sudo_group }}"
      - users
    state: present
    append: true
    update_password: on_create

- name: Ensure group "{{ username }}" exists
  become: yes
  group:
    name: "{{ username }}"
    state: present

- name: Copy the public SSH key
  become: yes
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"

- name: Clone the latest dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: /home/{{ username }}/.dotfiles
    recursive: no
    force: yes

- name: Stow the dotfiles
  shell: cd /home/{{ username }}/.dotfiles && stow -v */
  register: stow_result
  changed_when: stow_result.stdout != ""

- name: Set the default shell
  user:
    name: "{{ username }}"
    shell: "{{ shell }}"

- name: Disable fish greeting
  lineinfile:
    path: /home/{{ username }}/.config/fish/fish_variables
    state: present
    regexp: 'fish_greeting:.+'
    line: 'SETUVAR fish_greeting:'
  when: '"fish" in shell'
  ignore_errors: true

- name: Set the correct ownership for the user's home folder (not using ansible.builtin.file because of idempotency)
  shell:
    cmd: "chown -R {{ username }}:{{ username }} /home/{{ username }}"
  register: chown_status
  changed_when: chown_status.stdout != ""

- name: Suppress login messages
  file:
    name: /home/{{ username }}/.hushlogin
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: 0644
