---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install extra packages
  package:
    name: "{{ filesystem_packages }}"
    state: present

- include_tasks: nfs.yml
