---
- name: Install NFS mount on Non-LXC hosts
  block:
    - include_tasks: nfs.yml
  when: "'lxc' not in ansible_virtualization_type"

- name: Intall bind mount on LXC hosts
  block:
    - include_tasks: bind-mount.yml
  when: "'lxc' in ansible_virtualization_type"
