---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install required system packages
  package:
    state: present
    name: "{{ docker_deps }}"

- include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ username }}" to group docker
  user:
    name: '{{ username }}'
    groups:
      - docker
    append: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Get a list of installed containers
  command: docker ps --format "{{ '{{' }} .Names {{ '}}' }}"
  changed_when: false
  register: containers

- include_tasks: uninstall-container.yml
  with_items: "{{ containers.stdout_lines }}"
  when: item not in selected_containers

- include_tasks: prepare-persistant-data.yml
